In [14]:
import numpy as np
a = np.random.normal(size=(10))
#print(a, np.sign(0))
a, np.where(a > 0, np.exp(a), a)

(array([-0.17847662, -1.83280428,  0.73804701,  1.8754532 , -0.5777327 ,
         0.29276659,  0.50290364,  2.4367856 , -0.06986195, -1.57085478]),
 array([-0.17847662, -1.83280428,  2.09184616,  6.52377503, -0.5777327 ,
         1.34012995,  1.65351553, 11.43622101, -0.06986195, -1.57085478]))

In [8]:
from python.dataset.dataset import Dataset

a = Dataset('name', 'mode')

AttributeError: type object 'Dataset' has no attribute 'str'

In [2]:
import numpy as np

In [3]:
from python.activation import activations

activations.softmax(np.random.normal(size=(10, 15)))


AttributeError: 'numpy.ndarray' object has no attribute '_logits'

In [2]:
activations.get('relu')

<function python.activation.activations.relu(x)>

In [37]:
import numpy as np
a = np.random.normal(size=(2, 15))
m = np.max(a, axis=-1,keepdims=True)
a.shape, m.shape

((2, 15), (2, 1))

In [40]:
m = m + np.arange(2).reshape((-1, 1))

In [41]:
a.shape, m.shape

((2, 15), (2, 1))

In [45]:
a[0], m[0], (a - m)[0]

(array([ 0.68352835, -0.64763464, -2.39643835,  0.32157915,  1.9558096 ,
        -0.30142302,  0.03578232, -2.09060247,  0.9779089 , -0.4097147 ,
         1.57259587,  0.4691798 ,  0.17594425,  0.68349193, -0.89320661]),
 array([1.9558096]),
 array([-1.27228125, -2.60344424, -4.35224795, -1.63423045,  0.        ,
        -2.25723262, -1.92002728, -4.04641207, -0.9779007 , -2.3655243 ,
        -0.38321373, -1.4866298 , -1.77986535, -1.27231767, -2.84901621]))

In [47]:
diff = a - m
exp = np.exp(diff)
sum_exp = np.sum(exp, axis=-1, keepdims=True)
diff.shape, exp.shape, sum_exp.shape

((2, 15), (2, 15), (2, 1))

In [53]:
output = exp / sum_exp

exp[0], sum_exp[0], output[0]

(array([0.28019171, 0.0740182 , 0.01287783, 0.19510245, 1.        ,
        0.10463966, 0.14660296, 0.017485  , 0.37609982, 0.09390006,
        0.68166719, 0.22613349, 0.16866086, 0.2801815 , 0.05790126]),
 array([3.71546198]),
 array([0.07541235, 0.01992167, 0.00346601, 0.05251095, 0.26914553,
        0.0281633 , 0.03945753, 0.00470601, 0.10122559, 0.02527278,
        0.18346768, 0.06086282, 0.04539432, 0.0754096 , 0.01558386]))